name: Prep Decaf Release

on:
    push:
        branches: [prep-decaf]

jobs:
    prep-decaf-release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the commit
              uses: actions/checkout@v2

            - name: Version bump
              id: bump-version
              uses: eventespresso/actions/packages/version-bump@main
              with:
                  type: decaf
                  main-file: espresso.php
                  readme-file: readme.txt
                  info-json-file: info.json

            - name: Get decaf files to remove
              id: files-to-remove
              uses: eventespresso/actions/packages/json-prop@main
              with:
                  file-path: info.json
                  prop-path: decafFilesRemove
                  output-as-json: true

            - name: Remove files/directories
              uses: eventespresso/actions/packages/remove-files@main
              with:
                  paths: ${{ steps.files-to-remove.outputs.value }}

            - name: Generate POT
              uses: eventespresso/actions/packages/makepot@main
              with:
                  save-path: languages
                  slug: event-espresso-core
                  text-domain: event_espresso

            - name: Create Tag
              uses: negz/create-tag@v1
              with:
                version: ${{ steps.bump-version.outputs.new-version }}
                message: Decaf ${{ steps.bump-version.outputs.new-version }}
                token: ${{ secrets.GITHUB_TOKEN }}

            - name: Build
              run: |
                npm install
                npm run build

            - name: WordPress Plugin Deploy
              id: deploy
              uses: 10up/action-wordpress-plugin-deploy@stable
              with:
                generate-zip: true
              env:
                SLUG: event-espresso-decaf
                SVN_USERNAME: ${{ secrets.WORDPRESS_ORG_USERNAME }}
                SVN_PASSWORD: ${{ secrets.WORDPRESS_ORG_PASSWORD }}

            - name: Upload release asset
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ github.event.release.upload_url }}
                asset_path: ${{ steps.deploy.outputs.zip-path }}
                asset_name: ${{ steps.bump-version.outputs.new-version }}.zip
                asset_content_type: application/zip
