name: Prep Decaf Release

on:
    push:
        branches: [prep-decaf]

jobs:
    prep-decaf-release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the commit
              uses: actions/checkout@v2

            - name: Get decafFilesRemove
              id: files-to-remove
              uses: eventespresso/actions/packages/json-prop@main
              with:
                  file-path: info.json
                  prop-path: decafFilesRemove
                  output-as-json: true

            - name: Remove files/directories
              uses: eventespresso/actions/packages/remove-files@main
              with:
                  paths: ${{ steps.files-to-remove.outputs.value }}

            - name: Generate POT
              uses: eventespresso/actions/packages/makepot@main
              with:
                  save-path: languages
                  slug: event-espresso-decaf
                  text-domain: event_espresso
